config/routes.rb
Goalkeeper::Application.routes.draw do

  resources :users, :goals, :atoms

  root :to => 'gk#index', :as => :index
  get "feed" => "gk#feed", :as => :feed

  get "login" => "auth#login", :as => :login
  get "logout" => "auth#logout", :as => :logout
  post "do_login" => "auth#do_login", :as => :do_login

  get 'login/venmo' => "auth#venmo", :as => :venmo

  get  'authorization' => 'auth#authorization'
  post 'authorization' => 'auth#authorization'

  post 'goals/new/commitment' => 'goals#commitment', :as => :commitment
  post 'goals/new/action' => 'goals#action', :as => :action

  get 'goals/:id/atoms' => 'goals#atoms'

  get 'goals/:id/success/' => 'atoms#success', :as => :success
  get 'goals/:id/failure/' => 'atoms#failure', :as => :failure

  post 'proof' => 'atoms#proof'
  post 'paid' => 'atoms#paid'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :birthday, :email, :first, :gender, :last, :password, :password_confirmation
  validates :email, :presence => true, :uniqueness => true
  validates :first, :presence => true
  validates :last, :presence => true
  validates :gender, :presence => true
  validates :birthday, :presence => true
  validates :password, :presence => true, :confirmation => true

  has_many :goals
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :get_logged_in_user, :except => [:new, :create]

	def index
		@users = User.all
	end

	def new
    @user = User.new
  end

  def create
	  @user = User.new(params[:user])
	 
    if @user.save
    	session[:user_id] = @user.id
      redirect_to venmo_url
    else
      render action: 'new'
    end
	  
	end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to users_url
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>users</hi>

<h2> List of People </h2>
<ul>
<% @users.each do |user| %>
<li>
<%= user.first %> (<%= link_to "View", user %>, <%= link_to "Edit", edit_user_url(user) %>, 
  <%= link_to "Delete", user_url(user), method: 'delete' %>)
</li>
<% end %>
</ul>
<%= link_to "Add a New user", new_user_url %>

	

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="sign-up">
  <%= form_for @user do |f| %>
   <% if @user.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <%= f.text_field :email, placeholder: 'Email', class: "email" %><br />
    <%= f.text_field :first, placeholder: 'First Name', class: "name" %><br />
    <%= f.text_field :last, placeholder: 'Last Name', class: "name" %><br />
    <%= f.label :birthday, "Birthday" %> <%= f.date_select :birthday, :start_year => 1970, :end_year => Time.now.year %><br />
    <%= f.label :gender, "Gender" %> <%= f.select :gender, [["Male", "male"], ["Female", "female"], ["Other", "other"]] %><br />
    <%= f.password_field :password, placeholder: "Password", class: "password" %> <br />
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "password" %>  <br />
    <%= f.submit class: "button submit" %>
  <% end %>

  <div class="new-user">
    <%= link_to "Cancel", index_url %>
  </div>

</div>