config/routes.rb
Goalkeeper::Application.routes.draw do

  resources :users, :goals, :atoms

  root :to => 'gk#index', :as => :index
  get "feed" => "gk#feed", :as => :feed

  get "login" => "auth#login", :as => :login
  get "logout" => "auth#logout", :as => :logout
  post "do_login" => "auth#do_login", :as => :do_login

  get 'login/venmo' => "auth#venmo", :as => :venmo

  get  'authorization' => 'auth#authorization'
  post 'authorization' => 'auth#authorization'

  post 'goals/new/commitment' => 'goals#commitment', :as => :commitment
  post 'goals/new/action' => 'goals#action', :as => :action

  get 'goals/:id/atoms' => 'goals#atoms'

  get 'goals/:id/success/' => 'atoms#success', :as => :success
  get 'goals/:id/failure/' => 'atoms#failure', :as => :failure

  post 'proof' => 'atoms#proof'
  post 'paid' => 'atoms#paid'

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :action, :charity, :duration, :frequency
  validates :action, :presence => true
  validates :charity, :presence => true
  validates :duration, :presence => true
  validates :frequency, :presence => true
  
  belongs_to :user
  has_many :atoms
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

	before_filter :get_logged_in_user

	def index
		user = User.find session[:user_id]
		@goals = user.goals
	end

	def new
    @goal = Goal.new
  end

	def commitment
		@goal = Goal.new
		@goal.user = User.find session[:user_id]
		@goal.charity = params[:charity]
		@goal.action = 'tbd'
		@goal.duration = '1'
		@goal.frequency = 'everyday'
	 
    if !@goal.save
      render action: 'new'
    end
	end

	def action
		duration = params[:duration]
		@disp = params
		frequency = ''
		if params[:SUN] == "1"
			frequency += "Su"
		end
		if params[:MON] == "1"
			frequency += "M"
		end
		if params[:TUE] == "1"
			frequency += "Tu"
		end
		if params[:WED] == "1"
			frequency += "W"
		end
		if params[:THU] == "1"
			frequency += "Th"
		end
		if params[:FRI] == "1"
			frequency += "F"
		end
		if params[:SAT] == "1"
			frequency += "Sa"
		end

		#@disp = frequency
		#frequency = params[:SU] + params[:M] + params[:TU] + params[:W] + params[:TH] + params[:F] + params[:SA]

		if frequency == "MTuWThF"
			frequency = "weekdays"
		elsif frequency == "SaSu"
			frequency = "weekends"
		elsif frequency == "SuMTuWThFSa"
			frequency = "everyday"
		end

		@goal = Goal.find params[:id]
		@goal.duration = duration
		@goal.frequency = frequency
		@goal.save
	end

	def create
		action = params[:goal_action]

		@goal = Goal.find params[:id]
		@goal.action = action
		@goal.save

		wdays = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
		months = [["Jan",31], ["Feb", 28], ["Mar", 31], ["Apr", 30], ["May", 31], ["Jun", 30], ["Jul", 31], ["Aug", 31], ["Sep", 30], ["Oct", 31], ["Nov", 30], ["Dec", 31]]

		wday = Time.now.wday - 1
		day = Time.now.day
		year = Time.now.year
		month = Time.now.month - 1

		@count = 28 * @goal.duration.to_i

		for current_iteration_number in 1..@count do
			wday = (wday + 1)%7
			if day == months[month][1]
				day = 1
				month = (month + 1)%12
				if month == 0
					year += 1
				end
			  if year%4 == 0 and month = 2
			  	day = 29
			  	month = 1
			  end
			elsif day == 29 and month == 1
				day = 1
				month = 2
			else
				day += 1
			end

		  atom = Atom.new
		  atom.goal = @goal
		  atom.day = day
		  atom.month = months[month][0]
		  atom.year = year

		  if @goal.frequency == "weekends" and (wday != 5 and wday != 6)
		  	atom.ignore = true

		  elsif @goal.frequency == "weekdays" and (wday == 5 or wday == 6)
		  	atom.ignore = true

		  elsif @goal.frequency != "everyday"
		  	if @goal.frequency.include? "M" and wday == 0
		  		atom.ignore = true
		  	end
		  	if @goal.frequency.include? "Tu" and wday == 1
		  		atom.ignore = true
		  	end
		  	if @goal.frequency.include? "W" and wday == 2
		  		atom.ignore = true
		  	end
		  	if @goal.frequency.include? "Th" and wday == 3
		  		atom.ignore = true
		  	end
		  	if @goal.frequency.include? "F" and wday == 4
		  		atom.ignore = true
		  	end
		  	if @goal.frequency.include? "Sa" and wday == 5
		  		atom.ignore = true
		  	end
		  	if @goal.frequency.include? "Su" and wday == 6
		  		atom.ignore = true
		  	end
		  end

		  atom.save
		end

		redirect_to goals_url
	end

	def destroy
    @goal = Goal.find params[:id]
    @goal.atoms.each do |atom|
    	atom.destroy
    end
    @goal.destroy
    redirect_to goals_url
  end

	def show
		@goal = Goal.find params[:id]
	end

	def atoms
		@goal = Goal.find params[:id]
		@atoms = @goal.atoms
	end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/action.html.erb
<%= form_tag action: "create" do %>
	<p>I will</p>
  <%= text_field_tag(:goal_action) %>
	<%= hidden_field_tag(:id, @goal.id) %>
	<p>

		<% if @goal.frequency == "everyday" %>
			    every day
			 <% elsif @goal.frequency == "weekends" %>
			 	 on the weekends
			 <% elsif @goal.frequency == "weekdays" %>
			 	 during the week
			 <% end %>

			 for

			 <% if @goal.duration == "1" %>
			 	 one month.
			 <% elsif @goal.duration == "3" %>
			 	 three months.
			 <% else %>
			 	 six months.
			 <% end %>
			 


	</p>
  <%= submit_tag "Set a goal!", class: "button submit" %>
<% end %>

app/views/goals/atoms.html.erb
<h1>overall progress</h1>
  <table class="progress-table">
	<% count = 0; %>
	<%  @atoms.each do |atom| %>

	<% if count == 0 %>
	  <tr>
	<% end %>

	     <td>
	     	<% if atom.ignore %>
		     	<%= link_to edit_atom_url(atom) do %>
		     		<%= image_tag "ignore.png" %>
		     	<% end %>
		    <% elsif !atom.completed %>
		      <%= link_to edit_atom_url(atom) do %>
		     		<%= image_tag "empty.png" %>
		     	<% end %>
		    <% elsif atom.success %>
		      <%= link_to edit_atom_url(atom) do %>
		     		<%= image_tag "succeed.png" %>
		     	<% end %>
		    <% else %>
		      <%= link_to edit_atom_url(atom) do %>
		     		<%= image_tag "fail.png" %>
		     	<% end %>
		    <% end %>

	     <div class="day"><%= atom.month + ' ' + atom.day.to_s %></div>
	  	 </td>

	<% if count == 3 %>
	   </tr>
	<% end %>

	<% count = (count + 1)%4 %>

	<% end %>

  </table>

app/views/goals/commitment.html.erb
<h1>commitment</h1>

<%= form_tag action: "action" do %>
<p>How long is your goal?</p>
  <div class="dur-buttons">
  <%= radio_button_tag :duration, "1", true, id: "dur-one" %>
	<%= label_tag :duration_one, "One Month" %><br>
	<%= radio_button_tag :duration, "3", false, id: "dur-three" %>
	<%= label_tag :duration_three, "Three Months" %><br>
	<%= radio_button_tag :duration, "6", false, id: "dur-six" %>
	<%= label_tag :duration_six, "Six Months" %><br></div>
	<div></div><br>
	<p>Which days of the week?</p>
	<div class="freq-buttons">
		<%= check_box_tag(:SUN) %>
		<%= label_tag(:SUN, "Su") %>
		<%= check_box_tag(:MON) %>
		<%= label_tag(:MON, "M") %>
		<%= check_box_tag(:TUE) %>
		<%= label_tag(:TUE, "Tu") %>
		<%= check_box_tag(:WED) %>
		<%= label_tag(:WED, "W") %>
		<%= check_box_tag(:THU) %>
		<%= label_tag(:THU, "Th") %>
		<%= check_box_tag(:FRI) %>
		<%= label_tag(:FRI, "F") %>
		<%= check_box_tag(:SAT) %>
		<%= label_tag(:SAT, "Sa") %>
	</div>
	<%= hidden_field_tag(:id, @goal.id) %>
  <%= submit_tag "Let's Do It", class: "button submit" %>
<% end %>
<div class="new-user"><%= link_to "Cancel", goals_url %></div>

<script type="text/javascript">
  $("#dur-one").click( function() {
  	$("dur").innerHTML("one month");
  });
  $("#dur-three").click( function() {
  	$("dur").innerHTML("three months");
  });
  $("#dur-six").click( function() {
  	$("dur").innerHTML("six months");
  });
</script>

app/views/goals/index.html.erb
<h1>my goals</h1>

<ul class="goals">
<% @goals.each do |goal| %>
<li>

<div class="action">Did you <i><%= goal.action %></i> today?</div>

<!--(%= link_to "Delete", goal_url(goal), method: 'delete' %)-->


<div class="success"><%= link_to "Yes", success_url(goal) %></div><div class="failure"><%= link_to "No", failure_url(goal) %></div><div class="progress"><%= link_to "Progress", goal %></div>
  
</li>
<% end %>
</ul>
<%= link_to "Add a New Goal", new_goal_url, class: "button" %>

app/views/goals/new.html.erb
<h1> Plan a New Goal </h1>

<%= form_for @goal, url: {action: "commitment"} do |f| %>
  <p>Start by selecting your charity</p>
  <div class="people">
    <div class="person AmericanHeartAssociation" data-id="AmericanHeartAssociation">
      <div class="friend-profile" style="background:url(<%= asset_path 'AHA.jpg' %>);background-size:50px 50px;">
      </div><p>American Heart Association</p>
      <input type="checkbox" id="AmericanHeartAssociation" name="charity" value="AmericanHeartAssociation" >
    </div>
    <div class="person possible" data-id="possible">
      <div class="friend-profile" style="background:url(<%= asset_path 'possible.jpg' %>);background-size:50px 50px;">
      </div><p>Possible Health</p>
      <input type="checkbox" id="possible" name="charity" value="possible" >
    </div>
    <div class="person givedirectly" data-id="givedirectly">
      <div class="friend-profile" style="background:url(<%= asset_path 'GiveDirectly.jpg' %>);background-size:50px 50px;">
      </div><p>GiveDirectly</p>
      <input type="checkbox" id="givedirectly" name="charity" value="givedirectly" >
    </div>
    <div class="person malarianomore" data-id="malarianomore">
      <div class="friend-profile" style="background:url(<%= asset_path 'MNM.jpg' %>);background-size:50px 50px;">
      </div><p>Malaria No More</p>
      <input type="checkbox" id="malarianomore" name="charity" value="malarianomore" >
    </div>
  </div>
  <%= f.submit "Select", class: "button submit" %>
<% end %>

<div class="new-user">
<%= link_to "Cancel", goals_url %>
</div>

<script type="text/javascript">
$( ".person" ).click( function() {
  $(".AmericanHeartAssociation").removeClass("selected");
  $(".possible").removeClass("selected");
  $(".givedirectly").removeClass("selected");
  $(".malarianomore").removeClass("selected");

  var person = $(this);
  person.addClass("selected");
  var id = person.attr("data-id");

  if (person.hasClass("selected")) $("input#" + id).prop('checked', true);
  else $("input#" + id).prop('checked', false);
});
</script>

app/views/goals/show.html.erb
<h1>You want to <i><%= @goal.action %></i>.</h1>
<div class="percent-success">
	<canvas id="myChart" width="100%" height="100%"></canvas>
</div><div class="amount-spent">
	<div class="amount">$100</div>
</div>
<div class="caption">
	Percent success rate
</div><div class="caption">
  Amount donated
</div>

<div class="progress-bar">
	<div class="progress">
	</div>
</div>
<div class="caption-full">Progress so far</div>

<h2>

<%= javascript_include_tag "Chart.min.js" %>
<script type="text/javascript">
var ctx = document.getElementById("myChart").getContext("2d");
var data = [
    {
        value: 300,
        color:"#F7464A",
        highlight: "#FF5A5E",
        label: "Failure"
    },
    {
        value: 50,
        color: "#8AB839",
        highlight: "#94C53D",
        label: "Success"
    }
];
var myDoughnutChart = new Chart(ctx).Doughnut(data,{

    //Number - The percentage of the chart that we cut out of the middle
    percentageInnerCutout : 50, // This is 0 for Pie charts

    //Number - Amount of animation steps
    animationSteps : 100,

    //String - Animation easing effect
    animationEasing : "easeOutBounce",

    //Boolean - Whether we animate the rotation of the Doughnut
    animateRotate : true,

    //Boolean - Whether we animate scaling the Doughnut from the centre
    animateScale : false });
</script>