config/routes.rb
Goalkeeper::Application.routes.draw do

  resources :users, :goals, :atoms

  root :to => 'gk#index', :as => :index
  get "feed" => "gk#feed", :as => :feed

  get "login" => "auth#login", :as => :login
  get "logout" => "auth#logout", :as => :logout
  post "do_login" => "auth#do_login", :as => :do_login

  get 'login/venmo' => "auth#venmo", :as => :venmo

  get  'authorization' => 'auth#authorization'
  post 'authorization' => 'auth#authorization'

  post 'goals/new/commitment' => 'goals#commitment', :as => :commitment
  post 'goals/new/action' => 'goals#action', :as => :action

  get 'goals/:id/atoms' => 'goals#atoms'

  get 'goals/:id/success/' => 'atoms#success', :as => :success
  get 'goals/:id/failure/' => 'atoms#failure', :as => :failure

  post 'proof' => 'atoms#proof'
  post 'paid' => 'atoms#paid'

end

app/controllers/gk_controller.rb
class GkController < ApplicationController
	before_filter :get_logged_in_user, :except => [:index]
  
  def index
  end

  def feed
  end  

end

app/helpers/gk_helper.rb
module GkHelper
end

app/views/gk/feed.html.erb
<h1>newsfeed</h1>

<%= link_to "Go to my goals", goals_url, class: "button" %>
<br>
<div style="background:url(<%= asset_path 'erin.jpg' %>);background-size:50px 50px;height:50px;width:50px; margin: 15px; float:left">
</div>
<div style="float:left">
	<p>Erin Hoffman</p>
</div>
<div style="clear:both">
	<ziggeo 
		ziggeo-video='8f9c90dc243060eef9f4631b7e07d61d' 
		ziggeo-width=500>
	</ziggeo>
</div>
<div style="background:url(<%= asset_path 'caitlin.jpg' %>);background-size:50px 50px;height:50px;width:50px; margin: 15px; float:left">
</div>
<div style="float:left">
	<p>Caitlin McDonald</p>
</div>
<div style="clear:both">
	<ziggeo 
		ziggeo-video='61a5b21876f95b697cd390436ea9d113' 
		ziggeo-width=500>
	</ziggeo>
</div>

app/views/gk/index.html.erb
<div class="center-logo">
	<%= image_tag "icon_greenNblack.png", alt: "goalkeeper logo" %>
</div>
<h1 class="landing-title">goalkeeper</h1>

<div class="login-control">
	<% if session[:user_id].nil? %>
	<%= link_to "Log In", login_url, class: "button" %>
	<%= link_to "Sign Up", new_user_url, class: "button" %>
	<% else %>
	<%= link_to "Log Out", logout_url, class: "button"  %>
	<% end %>
</div>


<style>
  #core {
  	background: black;
  }

  .header {
  	display: none;
  }
</style>