config/routes.rb
Goalkeeper::Application.routes.draw do

  resources :users, :goals, :atoms

  root :to => 'gk#index', :as => :index
  get "feed" => "gk#feed", :as => :feed

  get "login" => "auth#login", :as => :login
  get "logout" => "auth#logout", :as => :logout
  post "do_login" => "auth#do_login", :as => :do_login

  get 'login/venmo' => "auth#venmo", :as => :venmo

  get  'authorization' => 'auth#authorization'
  post 'authorization' => 'auth#authorization'

  post 'goals/new/commitment' => 'goals#commitment', :as => :commitment
  post 'goals/new/action' => 'goals#action', :as => :action

  get 'goals/:id/atoms' => 'goals#atoms'

  get 'goals/:id/success/' => 'atoms#success', :as => :success
  get 'goals/:id/failure/' => 'atoms#failure', :as => :failure

  post 'proof' => 'atoms#proof'
  post 'paid' => 'atoms#paid'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goalkeeper</title>
  <link href='http://fonts.googleapis.com/css?family=Abel|Rokkitt' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag "variables" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>  
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "//assets.ziggeo.com/css/ziggeo-betajs-player.min.css" %>
  <%= javascript_include_tag "//assets.ziggeo.com/js/ziggeo-jquery-json2-betajs-player.min.js" %>
  <%= favicon_link_tag 'icon_appicon.png', :rel => 'apple-touch-icon', :type => 'image/png' %>
  <%= favicon_link_tag 'icon_greenNwhite.png', :rel => 'shortcut icon', :type => 'image/png' %>
  <meta name="viewport" content="width=device-width, initial-scale = 1.0">
</head>
<body>

<div id="core">

  <div class="header">
    <div class="header-logo">
      <%= link_to feed_url do %>
        <%= image_tag('icon_greenNblack.png') %>
      <% end %>
    </div>
    <div class="header-title">
      <%= link_to "goalkeeper", :feed %>
    </div>

    <% unless session[:user_id].nil? %>
      <div class="logout">
        <%= link_to "Log Out", logout_url %>
      </div>
    <% end %>
  </div>

<%= yield %>

</div>
<%= javascript_include_tag "application" %>
</body>
</html>